### ISSUE TITLE
Setting the Kanban Board.

### ISSUE THREAD

**Issue by benwmx** [benwmx/Space-Travelers-Hub#25]
### Link to the repository : 
https://github.com/benwmx/Space-Travelers-Hub/projects/1

### the Team Members (2) : 
- @softwareengineermwi 
- @benwmx

**Comment by Emmyn5600** [comment]
Hi,

Good job so far! 👏🏼 @softwareengineermwi  and @benwmx 

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the project requirements.

 #### Optional suggestions
 
 - N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
